/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary:                    "#adc6ff",
        "primary-container":        "#4d8eff",
        "primary-fixed":            "#d8e2ff",
        "on-primary":               "#002e6a",
        "on-primary-container":     "#00285d",
        "inverse-primary":          "#005ac2",
        secondary:                  "#d0bcff",
        "secondary-container":      "#571bc1",
        "secondary-fixed":          "#e9ddff",
        "on-secondary":             "#3c0091",
        "on-secondary-container":   "#c4abff",
        tertiary:                   "#c9c6c5",
        "tertiary-container":       "#929090",
        "on-tertiary":              "#313030",
        "on-tertiary-container":    "#2a2a29",
        error:                      "#ffb4ab",
        "error-container":          "#93000a",
        "on-error":                 "#690005",
        surface:                    "#101415",
        "surface-dim":              "#101415",
        "surface-bright":           "#363a3b",
        "surface-container-lowest": "#0b0f10",
        "surface-container-low":    "#191c1e",
        "surface-container":        "#1d2022",
        "surface-container-high":   "#272a2c",
        "surface-container-highest":"#323537",
        "surface-variant":          "#323537",
        "on-surface":               "#e0e3e5",
        "on-surface-variant":       "#c2c6d6",
        "inverse-surface":          "#e0e3e5",
        "inverse-on-surface":       "#2d3133",
        outline:                    "#8c909f",
        "outline-variant":          "#424754",
      },
      fontFamily: {
        sans:  ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        mono:  ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        "2xl":   "1rem",
        "3xl":   "1.5rem",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%":      { transform: "translateY(-12px)" },
        },
        "pulse-ring": {
          "0%":   { boxShadow: "0 0 0 0 rgba(173,198,255,0.4)" },
          "70%":  { boxShadow: "0 0 0 8px rgba(173,198,255,0)" },
          "100%": { boxShadow: "0 0 0 0 rgba(173,198,255,0)" },
        },
      },
      animation: {
        float:        "float 6s ease-in-out infinite",
        "pulse-ring": "pulse-ring 2.2s ease-in-out infinite",
        "spin-slow":  "spin 8s linear infinite",
      },
    },
  },
  plugins: [],
};
